@echo off
echo Trocando para branch com as melhorias...
git checkout claude/fix-class-copy-schedule-gAVhC
echo Puxando atualizacoes...
git pull origin claude/fix-class-copy-schedule-gAVhC
echo Iniciando servidor...
npm run dev
